version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "tuesday"
      time: "08:00"
      timezone: "Asia/Tokyo"
    groups:
      dependencies:
        patterns:
          - "*"
    open-pull-requests-limit: 10
    assignees:
      - "k1LoW"
    commit-message:
      prefix: "chore"
      include: "scope"
